export interface SchemaColumn {
  name: string;
  type: string;
  primaryKey: boolean;
  foreignKey?: { targetTable: string; targetColumn: string };
  notNull: boolean;
  description: string;
}

export interface SchemaTable {
  id: string;
  name: string;
  schemaName: string;
  kind: 'table' | 'view';
  domain: string;
  description: string;
  columns: SchemaColumn[];
  x?: number;
  y?: number;
}

export interface SchemaRelationship {
  id: string;
  sourceTable: string;
  sourceColumn: string;
  targetTable: string;
  targetColumn: string;
  type: '1:1' | '1:N' | 'N:M';
  label: string;
}

export const EA_DATABASE_SCHEMA: {
  schemas: string[];
  tables: SchemaTable[];
  relationships: SchemaRelationship[];
} = {
  schemas: ['BT_BASE', 'public', 'admin'],
  tables: [
    // ------------------------------------------------------------------------
    // SECTION 1: ENTERPRISE ARCHITECTURE TABLES (Schema: BT_BASE)
    // ------------------------------------------------------------------------
    {
      id: 'capabilities',
      name: 'capabilities',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Capability Architecture',
      description: 'Multi-level business capability hierarchy with maturity and PACE classifications',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Authoritative capability GUID' },
        { name: 'workspace_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Multi-tenant workspace isolation partition' },
        { name: 'code', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Human-readable identifier (e.g. CAP-102)' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Canonical capability name' },
        { name: 'description', type: 'TEXT', primaryKey: false, notNull: false, description: 'Architectural scope and definition' },
        { name: 'parent_id', type: 'VARCHAR(64)', primaryKey: false, notNull: false, foreignKey: { targetTable: 'capabilities', targetColumn: 'id' }, description: 'Parent capability for L1-L4 hierarchy' },
        { name: 'level', type: 'INTEGER', primaryKey: false, notNull: true, description: 'Hierarchy depth (1=L1, 2=L2, 3=L3, 4=L4)' },
        { name: 'pace_layer', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Gartner PACE Layer (Record, Differentiation, Innovation)' },
        { name: 'strategic_importance', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Core Advantage, Differentiating, Commodity' },
        { name: 'current_maturity', type: 'NUMERIC(3,1)', primaryKey: false, notNull: true, description: 'Current maturity score (1.0 - 5.0)' },
        { name: 'target_maturity', type: 'NUMERIC(3,1)', primaryKey: false, notNull: true, description: 'Target maturity score (1.0 - 5.0)' },
        { name: 'investment_priority', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Invest, Tolerate, Modernize' },
        { name: 'risk_score', type: 'INTEGER', primaryKey: false, notNull: true, description: 'Composite operational risk (1-100)' },
        { name: 'business_owner', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Executive or Business Unit Owner' },
        { name: 'org_unit_id', type: 'VARCHAR(64)', primaryKey: false, notNull: false, foreignKey: { targetTable: 'org_units', targetColumn: 'id' }, description: 'Responsible Organization Unit' },
        { name: 'tags', type: 'JSONB', primaryKey: false, notNull: false, description: 'Array of contextual taxonomy tags' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Record creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Record modification timestamp' },
      ],
    },
    {
      id: 'value_streams',
      name: 'value_streams',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Value Stream Architecture',
      description: 'End-to-end customer-triggered value streams delivering tangible business outcomes',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Value stream unique identifier' },
        { name: 'workspace_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Tenant partition identifier' },
        { name: 'code', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Value stream code (e.g. VS-CORE-01)' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Value stream title' },
        { name: 'description', type: 'TEXT', primaryKey: false, notNull: false, description: 'Business context and journey narrative' },
        { name: 'type', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Core, Supporting, Management' },
        { name: 'trigger', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'External or internal triggering event' },
        { name: 'value_proposition', type: 'TEXT', primaryKey: false, notNull: true, description: 'Quantified stakeholder value created' },
        { name: 'stakeholder', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Primary receiving customer/partner' },
        { name: 'owner', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Value stream lead executive' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'value_stages',
      name: 'value_stages',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Value Stream Architecture',
      description: 'Sequential value stages with gating criteria, lead times, and flow efficiency',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Stage unique identifier' },
        { name: 'value_stream_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, foreignKey: { targetTable: 'value_streams', targetColumn: 'id' }, description: 'Parent value stream reference' },
        { name: 'order_index', type: 'INTEGER', primaryKey: false, notNull: true, description: 'Sequential pipeline order index' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Stage name' },
        { name: 'description', type: 'TEXT', primaryKey: false, notNull: false, description: 'Stage purpose and scope' },
        { name: 'entrance_criteria', type: 'TEXT', primaryKey: false, notNull: true, description: 'Gating condition to enter stage' },
        { name: 'exit_criteria', type: 'TEXT', primaryKey: false, notNull: true, description: 'Exit gating criterion' },
        { name: 'value_produced', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Tangible artifact or state output' },
        { name: 'lead_time_hours', type: 'NUMERIC(6,2)', primaryKey: false, notNull: true, description: 'Total calendar hours elapsed' },
        { name: 'processing_time_hours', type: 'NUMERIC(6,2)', primaryKey: false, notNull: true, description: 'Touch time value-adding hours' },
        { name: 'flow_efficiency_pct', type: 'NUMERIC(5,2)', primaryKey: false, notNull: true, description: 'Calculated flow efficiency percentage' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'value_stage_enabling_capabilities',
      name: 'value_stage_enabling_capabilities',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Value Stream Architecture',
      description: 'Many-to-many cross-reference linking value stream stages to enabling capabilities',
      columns: [
        { name: 'stage_id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, foreignKey: { targetTable: 'value_stages', targetColumn: 'id' }, description: 'Value stage foreign key' },
        { name: 'capability_id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, foreignKey: { targetTable: 'capabilities', targetColumn: 'id' }, description: 'Capability foreign key' },
      ],
    },
    {
      id: 'processes',
      name: 'processes',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Process & SIPOC Architecture',
      description: 'Business process catalog with automation metrics and operational execution parameters',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Process identifier' },
        { name: 'workspace_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Workspace isolation partition' },
        { name: 'code', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Process code (e.g. PRC-101)' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Process name' },
        { name: 'description', type: 'TEXT', primaryKey: false, notNull: false, description: 'Operational scope' },
        { name: 'category', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Core, Management, Support' },
        { name: 'trigger', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Triggering business event' },
        { name: 'end_state', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Terminal business outcome' },
        { name: 'owner', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Process owner / Workday Role' },
        { name: 'cycle_time_hours', type: 'NUMERIC(6,2)', primaryKey: false, notNull: true, description: 'Standard cycle time' },
        { name: 'automation_pct', type: 'NUMERIC(5,2)', primaryKey: false, notNull: true, description: 'STP automation rate %' },
        { name: 'cost_per_execution_usd', type: 'NUMERIC(8,2)', primaryKey: false, notNull: true, description: 'Cost per operational run' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'process_sipoc_steps',
      name: 'process_sipoc_steps',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Process & SIPOC Architecture',
      description: 'Canonical 5-box SIPOC (Suppliers, Inputs, Process, Outputs, Customers) step definitions',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'SIPOC step identifier' },
        { name: 'process_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, foreignKey: { targetTable: 'processes', targetColumn: 'id' }, description: 'Parent process foreign key' },
        { name: 'step_order', type: 'INTEGER', primaryKey: false, notNull: true, description: 'Step sequence number' },
        { name: 'step_name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Action step name' },
        { name: 'supplier', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Upstream provider / system' },
        { name: 'input_data', type: 'TEXT', primaryKey: false, notNull: true, description: 'Required input artifacts / data' },
        { name: 'process_action', type: 'TEXT', primaryKey: false, notNull: true, description: 'Transformation logic executed' },
        { name: 'output_artifact', type: 'TEXT', primaryKey: false, notNull: true, description: 'Produced artifact or state' },
        { name: 'customer_receiver', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Downstream recipient' },
      ],
    },
    {
      id: 'org_units',
      name: 'org_units',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Organization Architecture',
      description: 'Hierarchical organizational structure and business units',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Organization unit identifier' },
        { name: 'workspace_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Tenant partition identifier' },
        { name: 'code', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Org unit code (e.g. ORG-101)' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Unit name' },
        { name: 'type', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Division, Department, Squad' },
        { name: 'parent_id', type: 'VARCHAR(64)', primaryKey: false, notNull: false, foreignKey: { targetTable: 'org_units', targetColumn: 'id' }, description: 'Parent org unit in hierarchy' },
        { name: 'head_role', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Leader title / Workday profile' },
        { name: 'cost_center_code', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Workday Cost Center identifier' },
        { name: 'headcount_fte', type: 'NUMERIC(6,1)', primaryKey: false, notNull: true, description: 'Total allocated FTE headcount' },
        { name: 'location', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Primary geographic location' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'business_functions',
      name: 'business_functions',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Organization Architecture',
      description: 'Enterprise business functions and architectural ownership',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Function identifier' },
        { name: 'workspace_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Workspace partition' },
        { name: 'code', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Function code' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Function name' },
        { name: 'description', type: 'TEXT', primaryKey: false, notNull: false, description: 'Functional definition' },
        { name: 'parent_id', type: 'VARCHAR(64)', primaryKey: false, notNull: false, foreignKey: { targetTable: 'business_functions', targetColumn: 'id' }, description: 'Parent function' },
        { name: 'owner', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Functional owner' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'business_roles',
      name: 'business_roles',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Organization Architecture',
      description: 'Workday job profiles, standard labor rates, and headcount allocations',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Business role identifier' },
        { name: 'workspace_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Workspace identifier' },
        { name: 'code', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Role code' },
        { name: 'title', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Workday Job Profile title' },
        { name: 'org_unit_id', type: 'VARCHAR(64)', primaryKey: false, notNull: false, foreignKey: { targetTable: 'org_units', targetColumn: 'id' }, description: 'Parent org unit foreign key' },
        { name: 'workday_job_profile_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Authoritative Workday profile ID' },
        { name: 'standard_rate_usd', type: 'NUMERIC(8,2)', primaryKey: false, notNull: true, description: 'Hourly standard labor rate' },
        { name: 'allocated_fte', type: 'NUMERIC(4,2)', primaryKey: false, notNull: true, description: 'Allocated FTE capacity' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'business_services',
      name: 'business_services',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Capability Architecture',
      description: 'Business service catalog and SLA performance standards',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Service identifier' },
        { name: 'workspace_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Workspace isolation partition' },
        { name: 'code', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Service code' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Service name' },
        { name: 'description', type: 'TEXT', primaryKey: false, notNull: false, description: 'Service description' },
        { name: 'nature', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Internal, Customer-Facing, Partner' },
        { name: 'status', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Active, Deprecated, Pilot' },
        { name: 'owner_org_unit_id', type: 'VARCHAR(64)', primaryKey: false, notNull: false, foreignKey: { targetTable: 'org_units', targetColumn: 'id' }, description: 'Responsible org unit' },
        { name: 'owner_role', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Owner role' },
        { name: 'sla_availability_pct', type: 'NUMERIC(5,2)', primaryKey: false, notNull: true, description: 'Target SLA availability %' },
        { name: 'sla_response_time_hours', type: 'NUMERIC(5,2)', primaryKey: false, notNull: true, description: 'Target response time (hours)' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'products',
      name: 'products',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Capability Architecture',
      description: 'Commercial products, market segments, and pricing models',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Product identifier' },
        { name: 'workspace_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Workspace partition' },
        { name: 'code', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Product code' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Product title' },
        { name: 'description', type: 'TEXT', primaryKey: false, notNull: false, description: 'Product description' },
        { name: 'market_segment', type: 'VARCHAR(128)', primaryKey: false, notNull: true, description: 'Target market tier' },
        { name: 'pricing_model', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'SaaS, Subscription, Transactional' },
        { name: 'lifecycle_stage', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Growth, Mature, Sunset' },
        { name: 'product_manager', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Product manager name' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'strategic_goals',
      name: 'strategic_goals',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Strategy & OKRs',
      description: 'Strategic transformation goals with horizons, target metrics, and progress percentages',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Goal identifier' },
        { name: 'workspace_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Workspace isolation partition' },
        { name: 'code', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Goal code (e.g. GOAL-01)' },
        { name: 'title', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Strategic goal title' },
        { name: 'description', type: 'TEXT', primaryKey: false, notNull: false, description: 'Executive context' },
        { name: 'horizon_year', type: 'INTEGER', primaryKey: false, notNull: true, description: 'Target horizon year (e.g. 2026)' },
        { name: 'owner_role', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Executive sponsor role' },
        { name: 'target_metric', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Primary quantitative KPI target' },
        { name: 'progress_pct', type: 'NUMERIC(5,2)', primaryKey: false, notNull: true, description: 'Goal completion percentage' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'strategic_objectives',
      name: 'strategic_objectives',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Strategy & OKRs',
      description: 'Quarterly OKR objectives realizing strategic goals',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Objective unique identifier' },
        { name: 'workspace_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Workspace partition identifier' },
        { name: 'goal_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, foreignKey: { targetTable: 'strategic_goals', targetColumn: 'id' }, description: 'Parent strategic goal foreign key' },
        { name: 'code', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Objective code (e.g. OBJ-2026-Q1)' },
        { name: 'title', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Objective title' },
        { name: 'quarter', type: 'VARCHAR(16)', primaryKey: false, notNull: true, description: 'Execution quarter (e.g. 2026-Q1)' },
        { name: 'overall_progress_pct', type: 'NUMERIC(5,2)', primaryKey: false, notNull: true, description: 'Calculated OKR progress' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'transformation_initiatives',
      name: 'transformation_initiatives',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Roadmap & Horizons',
      description: 'Transformation portfolio initiatives classified by Three Horizons (H1, H2, H3) and budget',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Initiative identifier' },
        { name: 'workspace_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Workspace partition identifier' },
        { name: 'code', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Initiative code (e.g. INIT-01)' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Initiative name' },
        { name: 'horizon', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Horizon 1, Horizon 2, Horizon 3' },
        { name: 'budget_usd', type: 'NUMERIC(12,2)', primaryKey: false, notNull: true, description: 'Capital budget allocation (USD)' },
        { name: 'expected_roi_multiplier', type: 'NUMERIC(4,2)', primaryKey: false, notNull: true, description: 'Target ROI multiplier' },
        { name: 'status', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'In Flight, Approved, Backlog' },
        { name: 'lead_owner', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Program delivery manager' },
        { name: 'start_date', type: 'DATE', primaryKey: false, notNull: true, description: 'Scheduled start date' },
        { name: 'target_date', type: 'DATE', primaryKey: false, notNull: true, description: 'Target delivery date' },
      ],
    },
    {
      id: 'information_concepts',
      name: 'information_concepts',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'Information Architecture',
      description: 'Canonical enterprise information concepts, data criticality, and classification',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Concept identifier' },
        { name: 'workspace_id', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Workspace partition identifier' },
        { name: 'code', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Concept code (e.g. INF-101)' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Canonical concept name' },
        { name: 'domain', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Information domain' },
        { name: 'criticality', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Critical, High, Medium, Low' },
        { name: 'classification', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Confidential, Restricted, Public' },
        { name: 'canonical_definition', type: 'TEXT', primaryKey: false, notNull: true, description: 'Authoritative data definition' },
        { name: 'steward_role', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Data steward role' },
      ],
    },

    // ------------------------------------------------------------------------
    // SECTION 2: COPIED ENTERPRISE ARTIST DBA_ 3NF METAMODEL TABLES (Schema: BT_BASE)
    // ------------------------------------------------------------------------
    {
      id: 'dba_model_meta',
      name: 'dba_model_meta',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'DBA Metamodel Architecture',
      description: 'Canonical key-value project and model metadata table (copied from EA)',
      columns: [
        { name: 'key', type: 'VARCHAR(128)', primaryKey: true, notNull: true, description: 'Unique configuration key' },
        { name: 'value', type: 'TEXT', primaryKey: false, notNull: true, description: 'Metadata string value' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Last updated timestamp' },
      ],
    },
    {
      id: 'dba_fact_type_catalog',
      name: 'dba_fact_type_catalog',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'DBA Metamodel Architecture',
      description: 'Master fact sheet taxonomy catalog and visual appearance rules (copied from EA)',
      columns: [
        { name: 'code', type: 'VARCHAR(64)', primaryKey: true, notNull: true, description: 'Metamodel type code (Application, BusinessCapability, etc.)' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Display name' },
        { name: 'category', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Domain category' },
        { name: 'aspect', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'ArchiMate aspect classification' },
        { name: 'default_color', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Hex or HSL color code' },
        { name: 'icon_name', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Lucide icon identifier' },
        { name: 'description', type: 'TEXT', primaryKey: false, notNull: false, description: 'Catalog definition' },
      ],
    },
    {
      id: 'dba_fact_sheet',
      name: 'dba_fact_sheet',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'DBA Metamodel Architecture',
      description: 'Pure 3NF master architectural fact sheet repository table (copied from EA)',
      columns: [
        { name: 'id', type: 'SERIAL (INTEGER)', primaryKey: true, notNull: true, description: 'Primary internal integer key' },
        { name: 'external_id', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Unique external GUID' },
        { name: 'type', type: 'VARCHAR(64)', primaryKey: false, notNull: true, foreignKey: { targetTable: 'dba_fact_type_catalog', targetColumn: 'code' }, description: 'Foreign key to catalog' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Fact sheet title' },
        { name: 'full_name', type: 'VARCHAR(255)', primaryKey: false, notNull: false, description: 'Fully qualified name' },
        { name: 'display_name', type: 'VARCHAR(255)', primaryKey: false, notNull: false, description: 'Display title' },
        { name: 'description', type: 'TEXT', primaryKey: false, notNull: false, description: 'Architectural narrative' },
        { name: 'status', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Lifecycle status (ACTIVE, PLAN, PHASEOUT)' },
        { name: 'completion', type: 'NUMERIC(5,2)', primaryKey: false, notNull: true, description: 'Data completion percentage' },
        { name: 'level', type: 'INTEGER', primaryKey: false, notNull: true, description: 'Hierarchy level' },
        { name: 'quality_seal', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Governance seal status' },
        { name: 'lifecycle_state', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Live lifecycle state' },
        { name: 'parent_id', type: 'INTEGER', primaryKey: false, notNull: false, foreignKey: { targetTable: 'dba_fact_sheet', targetColumn: 'id' }, description: 'Parent fact sheet self-reference' },
        { name: 'owner', type: 'VARCHAR(255)', primaryKey: false, notNull: false, description: 'Responsible party' },
        { name: 'business_fit', type: 'NUMERIC(3,2)', primaryKey: false, notNull: false, description: 'Gartner Business Fit rating' },
        { name: 'technical_fit', type: 'NUMERIC(3,2)', primaryKey: false, notNull: false, description: 'Gartner Technical Fit rating' },
        { name: 'time_quadrant', type: 'VARCHAR(32)', primaryKey: false, notNull: false, description: 'TIME quadrant (TOLERATE, INVEST, MIGRATE, ELIMINATE)' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'dba_fact_property',
      name: 'dba_fact_property',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'DBA Metamodel Architecture',
      description: 'Normalized strongly-typed EAV property table without JSON blobs (copied from EA)',
      columns: [
        { name: 'id', type: 'SERIAL (INTEGER)', primaryKey: true, notNull: true, description: 'Property row primary key' },
        { name: 'fact_sheet_id', type: 'INTEGER', primaryKey: false, notNull: true, foreignKey: { targetTable: 'dba_fact_sheet', targetColumn: 'id' }, description: 'Parent fact sheet foreign key' },
        { name: 'property_key', type: 'VARCHAR(128)', primaryKey: false, notNull: true, description: 'Property attribute key' },
        { name: 'property_type', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Type descriptor (text, num, bool)' },
        { name: 'text_val', type: 'TEXT', primaryKey: false, notNull: false, description: 'Normalized text value' },
        { name: 'num_val', type: 'NUMERIC(12,4)', primaryKey: false, notNull: false, description: 'Normalized numeric value' },
        { name: 'bool_val', type: 'BOOLEAN', primaryKey: false, notNull: false, description: 'Normalized boolean value' },
        { name: 'unit', type: 'VARCHAR(32)', primaryKey: false, notNull: false, description: 'Measurement unit' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
      ],
    },
    {
      id: 'dba_fact_tag',
      name: 'dba_fact_tag',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'DBA Metamodel Architecture',
      description: 'Normalized fact sheet taxonomy tag linkages (copied from EA)',
      columns: [
        { name: 'id', type: 'SERIAL (INTEGER)', primaryKey: true, notNull: true, description: 'Tag row ID' },
        { name: 'fact_sheet_id', type: 'INTEGER', primaryKey: false, notNull: true, foreignKey: { targetTable: 'dba_fact_sheet', targetColumn: 'id' }, description: 'Parent fact sheet foreign key' },
        { name: 'tag_name', type: 'VARCHAR(128)', primaryKey: false, notNull: true, description: 'Tag identifier string' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
      ],
    },
    {
      id: 'dba_relation',
      name: 'dba_relation',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'DBA Metamodel Architecture',
      description: 'Direct 3NF graph topology relationships between fact sheets (copied from EA)',
      columns: [
        { name: 'id', type: 'SERIAL (INTEGER)', primaryKey: true, notNull: true, description: 'Relationship primary key' },
        { name: 'external_id', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Unique external relationship GUID' },
        { name: 'from_id', type: 'INTEGER', primaryKey: false, notNull: true, foreignKey: { targetTable: 'dba_fact_sheet', targetColumn: 'id' }, description: 'Source fact sheet foreign key' },
        { name: 'to_id', type: 'INTEGER', primaryKey: false, notNull: true, foreignKey: { targetTable: 'dba_fact_sheet', targetColumn: 'id' }, description: 'Target fact sheet foreign key' },
        { name: 'type', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Relationship metamodel type' },
        { name: 'description', type: 'TEXT', primaryKey: false, notNull: false, description: 'Relationship description' },
        { name: 'status', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Active status' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'dba_relation_property',
      name: 'dba_relation_property',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'DBA Metamodel Architecture',
      description: 'Normalized strongly-typed EAV property values for relationships (copied from EA)',
      columns: [
        { name: 'id', type: 'SERIAL (INTEGER)', primaryKey: true, notNull: true, description: 'Relation property ID' },
        { name: 'relation_id', type: 'INTEGER', primaryKey: false, notNull: true, foreignKey: { targetTable: 'dba_relation', targetColumn: 'id' }, description: 'Parent relation foreign key' },
        { name: 'property_key', type: 'VARCHAR(128)', primaryKey: false, notNull: true, description: 'Property attribute key' },
        { name: 'property_type', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'Type descriptor' },
        { name: 'text_val', type: 'TEXT', primaryKey: false, notNull: false, description: 'Text value' },
        { name: 'num_val', type: 'NUMERIC(12,4)', primaryKey: false, notNull: false, description: 'Numeric value' },
        { name: 'bool_val', type: 'BOOLEAN', primaryKey: false, notNull: false, description: 'Boolean value' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
      ],
    },
    {
      id: 'dba_view',
      name: 'dba_view',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'DBA Metamodel Architecture',
      description: 'Saved visual architecture diagram views and canvases (copied from EA)',
      columns: [
        { name: 'id', type: 'SERIAL (INTEGER)', primaryKey: true, notNull: true, description: 'View primary key' },
        { name: 'external_id', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Unique view GUID' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'View diagram name' },
        { name: 'view_type', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Layered, ApplicationLandscape, Matrix' },
        { name: 'description', type: 'TEXT', primaryKey: false, notNull: false, description: 'Diagram scope' },
        { name: 'layout_data', type: 'JSONB', primaryKey: false, notNull: false, description: 'Visual coordinates and zoom settings' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'dba_view_node',
      name: 'dba_view_node',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'DBA Metamodel Architecture',
      description: 'Positioning and visual layout for fact sheets on diagram canvases (copied from EA)',
      columns: [
        { name: 'id', type: 'SERIAL (INTEGER)', primaryKey: true, notNull: true, description: 'View node primary key' },
        { name: 'view_id', type: 'INTEGER', primaryKey: false, notNull: true, foreignKey: { targetTable: 'dba_view', targetColumn: 'id' }, description: 'Parent view foreign key' },
        { name: 'fact_sheet_id', type: 'INTEGER', primaryKey: false, notNull: true, foreignKey: { targetTable: 'dba_fact_sheet', targetColumn: 'id' }, description: 'Referenced fact sheet' },
        { name: 'x', type: 'NUMERIC(8,2)', primaryKey: false, notNull: true, description: 'X coordinate' },
        { name: 'y', type: 'NUMERIC(8,2)', primaryKey: false, notNull: true, description: 'Y coordinate' },
        { name: 'width', type: 'NUMERIC(8,2)', primaryKey: false, notNull: true, description: 'Node width' },
        { name: 'height', type: 'NUMERIC(8,2)', primaryKey: false, notNull: true, description: 'Node height' },
        { name: 'color', type: 'VARCHAR(32)', primaryKey: false, notNull: false, description: 'Custom color override' },
      ],
    },
    {
      id: 'dba_audit_log',
      name: 'dba_audit_log',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'DBA Metamodel Architecture',
      description: 'Immutable compliance audit trail for entity mutations (copied from EA)',
      columns: [
        { name: 'id', type: 'SERIAL (INTEGER)', primaryKey: true, notNull: true, description: 'Audit entry primary key' },
        { name: 'entity_type', type: 'VARCHAR(64)', primaryKey: false, notNull: true, description: 'Mutated entity type' },
        { name: 'entity_id', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Target entity GUID' },
        { name: 'action', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'CREATE, UPDATE, DELETE' },
        { name: 'actor', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'User or system identity' },
        { name: 'delta_json', type: 'JSONB', primaryKey: false, notNull: false, description: 'Diff payload' },
        { name: 'occurred_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Event timestamp' },
      ],
    },
    {
      id: 'dba_scenario',
      name: 'dba_scenario',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'DBA Metamodel Architecture',
      description: 'Strategic transformation and what-if architectural scenarios (copied from EA)',
      columns: [
        { name: 'id', type: 'SERIAL (INTEGER)', primaryKey: true, notNull: true, description: 'Scenario primary key' },
        { name: 'name', type: 'VARCHAR(255)', primaryKey: false, notNull: true, description: 'Scenario title' },
        { name: 'description', type: 'TEXT', primaryKey: false, notNull: false, description: 'Scenario hypothesis and narrative' },
        { name: 'status', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'DRAFT, APPROVED, REJECTED' },
        { name: 'created_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Creation timestamp' },
        { name: 'updated_at', type: 'TIMESTAMPTZ', primaryKey: false, notNull: true, description: 'Update timestamp' },
      ],
    },
    {
      id: 'dba_scenario_impact',
      name: 'dba_scenario_impact',
      schemaName: 'BT_BASE',
      kind: 'table',
      domain: 'DBA Metamodel Architecture',
      description: 'Cost and risk impact analysis per fact sheet in scenario (copied from EA)',
      columns: [
        { name: 'id', type: 'SERIAL (INTEGER)', primaryKey: true, notNull: true, description: 'Impact row primary key' },
        { name: 'scenario_id', type: 'INTEGER', primaryKey: false, notNull: true, foreignKey: { targetTable: 'dba_scenario', targetColumn: 'id' }, description: 'Parent scenario foreign key' },
        { name: 'fact_sheet_id', type: 'INTEGER', primaryKey: false, notNull: true, foreignKey: { targetTable: 'dba_fact_sheet', targetColumn: 'id' }, description: 'Impacted fact sheet foreign key' },
        { name: 'change_type', type: 'VARCHAR(32)', primaryKey: false, notNull: true, description: 'REPLACE, UPGRADE, DECOMMISSION' },
        { name: 'cost_impact_usd', type: 'NUMERIC(12,2)', primaryKey: false, notNull: false, description: 'Estimated financial impact' },
        { name: 'risk_level', type: 'VARCHAR(32)', primaryKey: false, notNull: false, description: 'HIGH, MEDIUM, LOW' },
        { name: 'notes', type: 'TEXT', primaryKey: false, notNull: false, description: 'Architect notes' },
      ],
    },
  ],
  relationships: [
    // BIZBOK Relationships
    {
      id: 'rel-cap-parent',
      sourceTable: 'capabilities',
      sourceColumn: 'parent_id',
      targetTable: 'capabilities',
      targetColumn: 'id',
      type: '1:N',
      label: 'Parent Hierarchy',
    },
    {
      id: 'rel-cap-org',
      sourceTable: 'capabilities',
      sourceColumn: 'org_unit_id',
      targetTable: 'org_units',
      targetColumn: 'id',
      type: '1:N',
      label: 'Managed By Org',
    },
    {
      id: 'rel-vs-stages',
      sourceTable: 'value_stages',
      sourceColumn: 'value_stream_id',
      targetTable: 'value_streams',
      targetColumn: 'id',
      type: '1:N',
      label: 'Composed of Stages',
    },
    {
      id: 'rel-stage-cap-stage',
      sourceTable: 'value_stage_enabling_capabilities',
      sourceColumn: 'stage_id',
      targetTable: 'value_stages',
      targetColumn: 'id',
      type: 'N:M',
      label: 'Realizes Stage',
    },
    {
      id: 'rel-stage-cap-cap',
      sourceTable: 'value_stage_enabling_capabilities',
      sourceColumn: 'capability_id',
      targetTable: 'capabilities',
      targetColumn: 'id',
      type: 'N:M',
      label: 'Enabling Capability',
    },
    {
      id: 'rel-proc-sipoc',
      sourceTable: 'process_sipoc_steps',
      sourceColumn: 'process_id',
      targetTable: 'processes',
      targetColumn: 'id',
      type: '1:N',
      label: 'SIPOC Step',
    },
    {
      id: 'rel-org-parent',
      sourceTable: 'org_units',
      sourceColumn: 'parent_id',
      targetTable: 'org_units',
      targetColumn: 'id',
      type: '1:N',
      label: 'Org Hierarchy',
    },
    {
      id: 'rel-role-org',
      sourceTable: 'business_roles',
      sourceColumn: 'org_unit_id',
      targetTable: 'org_units',
      targetColumn: 'id',
      type: '1:N',
      label: 'Assigned to Org',
    },
    {
      id: 'rel-goal-obj',
      sourceTable: 'strategic_objectives',
      sourceColumn: 'goal_id',
      targetTable: 'strategic_goals',
      targetColumn: 'id',
      type: '1:N',
      label: 'Realizes Goal',
    },
    // DBA Copied Relationships
    {
      id: 'rel-dba-fs-type',
      sourceTable: 'dba_fact_sheet',
      sourceColumn: 'type',
      targetTable: 'dba_fact_type_catalog',
      targetColumn: 'code',
      type: '1:N',
      label: 'Catalog Type',
    },
    {
      id: 'rel-dba-fs-parent',
      sourceTable: 'dba_fact_sheet',
      sourceColumn: 'parent_id',
      targetTable: 'dba_fact_sheet',
      targetColumn: 'id',
      type: '1:N',
      label: 'Parent Fact Sheet',
    },
    {
      id: 'rel-dba-prop-fs',
      sourceTable: 'dba_fact_property',
      sourceColumn: 'fact_sheet_id',
      targetTable: 'dba_fact_sheet',
      targetColumn: 'id',
      type: '1:N',
      label: 'Fact Property (EAV)',
    },
    {
      id: 'rel-dba-tag-fs',
      sourceTable: 'dba_fact_tag',
      sourceColumn: 'fact_sheet_id',
      targetTable: 'dba_fact_sheet',
      targetColumn: 'id',
      type: '1:N',
      label: 'Fact Tag',
    },
    {
      id: 'rel-dba-rel-from',
      sourceTable: 'dba_relation',
      sourceColumn: 'from_id',
      targetTable: 'dba_fact_sheet',
      targetColumn: 'id',
      type: '1:N',
      label: 'Source Fact Sheet',
    },
    {
      id: 'rel-dba-rel-to',
      sourceTable: 'dba_relation',
      sourceColumn: 'to_id',
      targetTable: 'dba_fact_sheet',
      targetColumn: 'id',
      type: '1:N',
      label: 'Target Fact Sheet',
    },
    {
      id: 'rel-dba-view-node',
      sourceTable: 'dba_view_node',
      sourceColumn: 'view_id',
      targetTable: 'dba_view',
      targetColumn: 'id',
      type: '1:N',
      label: 'View Canvas Layout',
    },
    {
      id: 'rel-dba-scenario-impact',
      sourceTable: 'dba_scenario_impact',
      sourceColumn: 'scenario_id',
      targetTable: 'dba_scenario',
      targetColumn: 'id',
      type: '1:N',
      label: 'Scenario Impact',
    },
  ],
};
