package memory

import (
	"time"

	"arch-base-deploy/internal/core/domain"
)

func (r *memoryRepository) seedDefaultEnterprise() {
	wsID := "ws-default"
	now := time.Now()

	r.workspaces[wsID] = domain.Workspace{
		ID:          wsID,
		Name:        "Global Enterprise Architecture Repository",
		Description: "Authoritative Enterprise Architecture Repository",
		Industry:    "Omnichannel Retail & Digital Financial Services",
		CreatedAt:   now,
		UpdatedAt:   now,
	}
	r.ensureWorkspaceMaps(wsID)

	// ── 1. Strategic Drivers, Goals, OKRs & Business Model Canvas ──
	r.drivers[wsID]["drv-01"] = domain.StrategicDriver{
		ID:          "drv-01",
		WorkspaceID: wsID,
		Code:        "DRV-DIGITAL-FIRST",
		Name:        "Accelerating Digital-First Consumer Expectations",
		Category:    domain.DriverCustomerExpect,
		ImpactLevel: "High",
		Description: "Consumers demand sub-second omni-channel checkout, personalized promotions, and instant credit verification.",
		CreatedAt:   now,
		UpdatedAt:   now,
	}
	r.drivers[wsID]["drv-02"] = domain.StrategicDriver{
		ID:          "drv-02",
		WorkspaceID: wsID,
		Code:        "DRV-COST-OPTIMIZE",
		Name:        "Operational Efficiency & Cost Containment",
		Category:    domain.DriverCostEfficiency,
		ImpactLevel: "High",
		Description: "Enterprise-wide target to reduce order processing cycle time by 40% and optimize supply chain fulfillment costs.",
		CreatedAt:   now,
		UpdatedAt:   now,
	}

	r.goals[wsID]["goal-01"] = domain.StrategicGoal{
		ID:           "goal-01",
		WorkspaceID:  wsID,
		Code:         "GOAL-OMNI-SCALE",
		Title:        "Scale Global Digital Revenue to $2.5B by 2027",
		Description:  "Expand digital touchpoints across EMEA and APAC with seamless mobile-first experiences.",
		DriverIDs:    []string{"drv-01"},
		HorizonYear:  2027,
		OwnerRole:    "Chief Commercial Officer",
		TargetMetric: "$2.5B Digital GMV",
		ProgressPct:  68.0,
		CreatedAt:    now,
		UpdatedAt:    now,
	}
	r.goals[wsID]["goal-02"] = domain.StrategicGoal{
		ID:           "goal-02",
		WorkspaceID:  wsID,
		Code:         "GOAL-SUPPLY-AGILITY",
		Title:        "Achieve Real-Time Automated Supply Chain & Fulfillment",
		Description:  "Automate inventory allocation, reduce order-to-delivery lead time to under 24 hours in metro zones.",
		DriverIDs:    []string{"drv-02"},
		HorizonYear:  2026,
		OwnerRole:    "Chief Operating Officer",
		TargetMetric: "< 24h Metro Delivery Lead Time",
		ProgressPct:  82.0,
		CreatedAt:    now,
		UpdatedAt:    now,
	}

	r.objectives[wsID]["obj-01"] = domain.StrategicObjective{
		ID:          "obj-01",
		WorkspaceID: wsID,
		GoalID:      "goal-01",
		Code:        "OBJ-2026-Q3-01",
		Title:       "Modernize Customer Onboarding & Digital Identity Verification",
		Description: "Reduce new customer checkout friction and automate instant identity verification.",
		Quarter:     "2026-Q3",
		KeyResults: []domain.KeyResult{
			{
				ID:           "kr-01",
				ObjectiveID:  "obj-01",
				Title:        "Reduce average onboarding drop-off rate from 28% to <10%",
				MetricName:   "Drop-off Rate",
				StartValue:   28.0,
				CurrentValue: 14.5,
				TargetValue:  9.5,
				Unit:         "%",
				ProgressPct:  72.0,
				Owner:        "VP Customer Experience",
				UpdatedAt:    now,
			},
		},
		ImpactedCapabilityIDs: []string{"cap-01", "cap-02"},
		OverallProgressPct:    72.0,
		CreatedAt:             now,
		UpdatedAt:             now,
	}
	r.objectives[wsID]["obj-02"] = domain.StrategicObjective{
		ID:          "obj-02",
		WorkspaceID: wsID,
		GoalID:      "goal-02",
		Code:        "OBJ-2026-Q3-02",
		Title:       "Implement Intelligent Multi-Warehouse Inventory Routing",
		Description: "Deploy automated demand forecasting and dynamic warehouse dispatching.",
		Quarter:     "2026-Q3",
		KeyResults: []domain.KeyResult{
			{
				ID:           "kr-02",
				ObjectiveID:  "obj-02",
				Title:        "Automate 90% of stock allocation decisions without manual dispatcher intervention",
				MetricName:   "Automated Dispatch %",
				StartValue:   35.0,
				CurrentValue: 78.0,
				TargetValue:  90.0,
				Unit:         "%",
				ProgressPct:  86.0,
				Owner:        "VP Supply Chain Operations",
				UpdatedAt:    now,
			},
		},
		ImpactedCapabilityIDs: []string{"cap-04", "cap-05"},
		OverallProgressPct:    86.0,
		CreatedAt:             now,
		UpdatedAt:             now,
	}

	r.canvas[wsID] = &domain.BusinessModelCanvas{
		ID:          "bmc-01",
		WorkspaceID: wsID,
		Name:        "Enterprise Omnichannel Commerce & Fintech Canvas",
		Version:     "v3.2",
		KeyPartners: []string{
			"Workday Enterprise Cloud",
			"Payment Gateway & Merchant Acquiring Networks",
			"Third-Party Logistics (3PL) & Metro Delivery Couriers",
			"Cloud & AI Infrastructure Providers",
		},
		KeyActivities: []string{
			"Omni-Channel Merchandising & Dynamic Pricing",
			"Algorithmic Inventory Allocation & Order Routing",
			"Digital Customer Acquisition & Loyalty Engagement",
			"Secure Real-Time Transaction Settlement",
		},
		KeyResources: []string{
			"Integrated E-Commerce Platform & Mobile Apps",
			"Centralized Distribution Centers & Micro-Fulfillment Hubs",
			"Customer 360 Information Model & Behavioral Graph",
			"Domain Architecture & Engineering Talent",
		},
		ValuePropositions: []string{
			"Same-day delivery on curated catalog items",
			"Zero-friction single-click biometric checkout",
			"Tailored personalized rewards & installment credit",
			"Transparent real-time tracking from warehouse to doorstep",
		},
		CustomerRelationships: []string{
			"Automated self-service mobile app",
			"Dedicated 24/7 VIP concierge support",
			"Omnichannel personalized messaging via SMS/Push/Email",
		},
		Channels: []string{
			"Native iOS & Android Mobile Apps",
			"Responsive Digital Web Portal",
			"Flagship Experience Retail Stores",
			"B2B Merchant Marketplace API",
		},
		CustomerSegments: []string{
			"High-Frequency Digital-Native Shoppers",
			"Enterprise Wholesale Accounts",
			"In-Store Retail Shoppers",
		},
		CostStructure: []string{
			"Fulfillment, Logistics & Last-Mile Transportation",
			"Cloud Infrastructure & Technology Maintenance",
			"Personnel, Store Operations & Facilities (Workday Managed)",
			"Marketing & Customer Acquisition",
		},
		RevenueStreams: []string{
			"Direct-to-Consumer (D2C) Product Sales",
			"Fintech Merchant Processing & Interchange Fees",
			"Premium Annual Loyalty Membership Subscriptions",
			"Marketplace Seller Commission & Fulfillment Fees",
		},
		CreatedAt: now,
		UpdatedAt: now,
	}

	// ── 2. Business Capabilities (L1 & L2 Hierarchy) ──
	r.capabilities[wsID]["cap-01"] = domain.Capability{
		ID:                  "cap-01",
		WorkspaceID:         wsID,
		Code:                "CAP-01",
		Name:                "Customer Relationship & Experience Management",
		Description:         "Ability to acquire, onboard, engage, and support enterprise and retail customers across all touchpoints.",
		Level:               domain.Level1,
		PaceLayer:           domain.PaceDifferentiation,
		StrategicImportance: domain.StrategicCore,
		CurrentMaturity:     3.8,
		TargetMaturity:      4.8,
		InvestmentPriority:  "High",
		RiskScore:           2.0,
		BusinessOwner:       "Chief Commercial Officer",
		Tags:                []string{"Customer", "CRM", "Front-Office"},
		CreatedAt:           now,
		UpdatedAt:           now,
	}
	r.capabilities[wsID]["cap-02"] = domain.Capability{
		ID:                  "cap-02",
		WorkspaceID:         wsID,
		Code:                "CAP-01.01",
		Name:                "Digital Customer Onboarding & KYC",
		Description:         "Automated capture of customer credentials, identity verification, and fraud scoring.",
		ParentID:            strPtr("cap-01"),
		Level:               domain.Level2,
		PaceLayer:           domain.PaceInnovation,
		StrategicImportance: domain.StrategicCore,
		CurrentMaturity:     3.2,
		TargetMaturity:      4.6,
		InvestmentPriority:  "High",
		RiskScore:           3.2,
		BusinessOwner:       "VP Digital Experience",
		Tags:                []string{"Onboarding", "Fintech", "Identity"},
		CreatedAt:           now,
		UpdatedAt:           now,
	}
	r.capabilities[wsID]["cap-03"] = domain.Capability{
		ID:                  "cap-03",
		WorkspaceID:         wsID,
		Code:                "CAP-01.02",
		Name:                "Personalized Loyalty & Rewards Management",
		Description:         "Calculation and redemption of customer loyalty points, tiered privileges, and real-time promotions.",
		ParentID:            strPtr("cap-01"),
		Level:               domain.Level2,
		PaceLayer:           domain.PaceDifferentiation,
		StrategicImportance: domain.StrategicDifferentiating,
		CurrentMaturity:     3.9,
		TargetMaturity:      4.5,
		InvestmentPriority:  "Medium",
		RiskScore:           1.8,
		BusinessOwner:       "VP Marketing Operations",
		Tags:                []string{"Loyalty", "Promotions"},
		CreatedAt:           now,
		UpdatedAt:           now,
	}
	r.capabilities[wsID]["cap-04"] = domain.Capability{
		ID:                  "cap-04",
		WorkspaceID:         wsID,
		Code:                "CAP-02",
		Name:                "Supply Chain, Inventory & Fulfillment",
		Description:         "End-to-end management of supplier procurement, multi-echelon inventory, and omnichannel fulfillment.",
		Level:               domain.Level1,
		PaceLayer:           domain.PaceRecord,
		StrategicImportance: domain.StrategicCore,
		CurrentMaturity:     4.1,
		TargetMaturity:      4.9,
		InvestmentPriority:  "High",
		RiskScore:           2.4,
		BusinessOwner:       "Chief Supply Chain Officer",
		Tags:                []string{"Logistics", "Inventory", "Operations"},
		CreatedAt:           now,
		UpdatedAt:           now,
	}
	r.capabilities[wsID]["cap-05"] = domain.Capability{
		ID:                  "cap-05",
		WorkspaceID:         wsID,
		Code:                "CAP-02.01",
		Name:                "Dynamic Inventory Allocation & Routing",
		Description:         "Algorithmic assignment of customer orders to nearest fulfillment centers or store locations.",
		ParentID:            strPtr("cap-04"),
		Level:               domain.Level2,
		PaceLayer:           domain.PaceInnovation,
		StrategicImportance: domain.StrategicCore,
		CurrentMaturity:     3.4,
		TargetMaturity:      4.8,
		InvestmentPriority:  "High",
		RiskScore:           2.8,
		BusinessOwner:       "VP Logistics",
		Tags:                []string{"Warehouse", "Fulfillment", "Routing"},
		CreatedAt:           now,
		UpdatedAt:           now,
	}
	r.capabilities[wsID]["cap-06"] = domain.Capability{
		ID:                  "cap-06",
		WorkspaceID:         wsID,
		Code:                "CAP-03",
		Name:                "Financial Settlement, Billing & Revenue Assurance",
		Description:         "Billing, payment authorization, multi-currency ledger recording, and Workday financial reconciliation.",
		Level:               domain.Level1,
		PaceLayer:           domain.PaceRecord,
		StrategicImportance: domain.StrategicParity,
		CurrentMaturity:     4.4,
		TargetMaturity:      4.8,
		InvestmentPriority:  "Maintain",
		RiskScore:           1.5,
		BusinessOwner:       "Chief Financial Officer",
		Tags:                []string{"Finance", "Workday", "Billing"},
		CreatedAt:           now,
		UpdatedAt:           now,
	}

	// ── 3. Value Streams & Stages ──
	r.valueStreams[wsID]["vs-01"] = domain.ValueStream{
		ID:               "vs-01",
		WorkspaceID:      wsID,
		Code:             "VS-ORDER-TO-FULFILL",
		Name:             "Customer Order to Fulfillment Journey",
		Type:             domain.ValueStreamCoreCustomer,
		Trigger:          "Customer confirms purchase in digital checkout",
		ValueProposition: "Accurate, rapid delivery with complete real-time tracking transparency",
		Stakeholder:      "E-Commerce Retail Customer",
		Owner:            "VP Omnichannel Operations",
		Stages: []domain.ValueStage{
			{
				ID:                  "stg-01",
				ValueStreamID:       "vs-01",
				OrderIndex:          1,
				Name:                "Order Capture & Payment Auth",
				Description:         "Validating basket items, applying promotions, and reserving funds on payment gateway.",
				EntranceCriteria:    "Customer clicks 'Place Order'",
				ExitCriteria:        "Payment pre-authorized & Order ID generated",
				ValueProduced:       "Authorized Order Record",
				LeadTimeHours:       0.05,
				ProcessingTimeHours: 0.04,
				FlowEfficiencyPct:   80.0,
				EnablingCapabilityIDs: []string{"cap-01", "cap-06"},
				EnablingCapabilities: []domain.CapabilitySummary{
					{ID: "cap-01", Code: "CAP-01", Name: "Customer Relationship Management", PaceLayer: domain.PaceDifferentiation, CurrentMaturity: 3.8},
					{ID: "cap-06", Code: "CAP-03", Name: "Financial Settlement & Billing", PaceLayer: domain.PaceRecord, CurrentMaturity: 4.4},
				},
				CreatedAt: now,
				UpdatedAt: now,
			},
			{
				ID:                  "stg-02",
				ValueStreamID:       "vs-01",
				OrderIndex:          2,
				Name:                "Inventory Allocation & Dispatching",
				Description:         "Routing order lines to optimal warehouse and reserving physical shelf stock.",
				EntranceCriteria:    "Order authorized and placed in routing queue",
				ExitCriteria:        "Pick list dispatched to warehouse management system",
				ValueProduced:       "Allocated Fulfillment Job",
				LeadTimeHours:       0.5,
				ProcessingTimeHours: 0.1,
				FlowEfficiencyPct:   20.0,
				EnablingCapabilityIDs: []string{"cap-04", "cap-05"},
				EnablingCapabilities: []domain.CapabilitySummary{
					{ID: "cap-04", Code: "CAP-02", Name: "Supply Chain & Fulfillment", PaceLayer: domain.PaceRecord, CurrentMaturity: 4.1},
					{ID: "cap-05", Code: "CAP-02.01", Name: "Dynamic Inventory Allocation", PaceLayer: domain.PaceInnovation, CurrentMaturity: 3.4},
				},
				CreatedAt: now,
				UpdatedAt: now,
			},
			{
				ID:                  "stg-03",
				ValueStreamID:       "vs-01",
				OrderIndex:          3,
				Name:                "Pick, Pack & Manifesting",
				Description:         "Physical picking of items, automated parcel packaging, and shipping label generation.",
				EntranceCriteria:    "Pick list active on warehouse terminal",
				ExitCriteria:        "Parcel scanned onto carrier shipping pallet",
				ValueProduced:       "Manifested Shipping Parcel",
				LeadTimeHours:       2.5,
				ProcessingTimeHours: 0.8,
				FlowEfficiencyPct:   32.0,
				EnablingCapabilityIDs: []string{"cap-04"},
				CreatedAt:           now,
				UpdatedAt:           now,
			},
			{
				ID:                  "stg-04",
				ValueStreamID:       "vs-01",
				OrderIndex:          4,
				Name:                "Last-Mile Carrier Delivery",
				Description:         "Transit by logistics partner with geo-location updates sent to customer.",
				EntranceCriteria:    "Carrier scans package at depot exit",
				ExitCriteria:        "Customer signature / photographic proof of delivery confirmed",
				ValueProduced:       "Fulfilled Customer Delivery",
				LeadTimeHours:       18.0,
				ProcessingTimeHours: 4.5,
				FlowEfficiencyPct:   25.0,
				EnablingCapabilityIDs: []string{"cap-01", "cap-04"},
				CreatedAt:           now,
				UpdatedAt:           now,
			},
		},
		CreatedAt: now,
		UpdatedAt: now,
	}

	// ── 4. Business Processes, SIPOC & RACI ──
	r.processes[wsID]["proc-01"] = domain.BusinessProcess{
		ID:                   "proc-01",
		WorkspaceID:          wsID,
		Code:                 "PROC-ORD-01",
		Name:                 "Automated Digital Order Processing & Settlement",
		Description:          "Core orchestrator processing inbound web/mobile orders through fraud checks, inventory reservation, and payment settlement.",
		Category:             domain.ProcessCore,
		Classification:       domain.ProcessAutomated,
		AssociatedCapabilityID: strPtr("cap-01"),
		AssociatedValueStageID: strPtr("stg-01"),
		OwnerRole:            "Director of E-Commerce Operations",
		SIPOC: domain.SIPOC{
			Suppliers: []string{"Customer Browser/App", "Payment Gateway", "Product Catalog Engine"},
			Inputs:    []string{"Encrypted Shopping Basket", "Payment Token", "Customer Delivery Address"},
			Outputs:   []string{"Confirmed Order Event", "Settlement Ledger Journal (Workday)", "Customer Email Receipt"},
			Customers: []string{"Customer", "Warehouse Dispatch Engine", "Workday Financials"},
		},
		Steps: []domain.ProcessStep{
			{
				ID:                 "step-01",
				ProcessID:          "proc-01",
				OrderIndex:         1,
				Name:               "Validate Pricing & Apply Promotions",
				Description:        "Re-verify cart prices against database and apply coupon discounts.",
				StepType:           "Task",
				CycleTimeMinutes:   0.02,
				AutomationScorePct: 100.0,
				RACIAssignments: []domain.RACIAssignment{
					{RoleID: "role-01", RoleName: "E-Commerce System Engine", Type: domain.RACIResponsible},
					{RoleID: "role-02", RoleName: "Director of Merchandising", Type: domain.RACIAccountable},
				},
			},
			{
				ID:                 "step-02",
				ProcessID:          "proc-01",
				OrderIndex:         2,
				Name:               "Authorize Payment Gateway",
				Description:        "Submit payment token to acquiring network for 3D Secure verification.",
				StepType:           "Task",
				CycleTimeMinutes:   0.05,
				AutomationScorePct: 100.0,
				RACIAssignments: []domain.RACIAssignment{
					{RoleID: "role-01", RoleName: "Payment Gateway Connector", Type: domain.RACIResponsible},
					{RoleID: "role-03", RoleName: "Treasurer / Fintech Officer", Type: domain.RACIAccountable},
				},
			},
			{
				ID:                 "step-03",
				ProcessID:          "proc-01",
				OrderIndex:         3,
				Name:               "Publish Order Placed Event",
				Description:        "Emit Kafka domain event for downstream inventory routing and customer confirmation.",
				StepType:           "Event",
				CycleTimeMinutes:   0.01,
				AutomationScorePct: 100.0,
				RACIAssignments: []domain.RACIAssignment{
					{RoleID: "role-01", RoleName: "Event Broker", Type: domain.RACIResponsible},
				},
			},
		},
		AvgCycleTimeMinutes:  0.08,
		OverallAutomationPct: 100.0,
		PainPoints:           []string{"Occasional payment gateway timeout during Black Friday peaks"},
		Tags:                 []string{"Checkout", "Core", "Automated"},
		CreatedAt:            now,
		UpdatedAt:            now,
	}

	// ── 5. Organization Units, Business Functions & Roles (Workday Aligned) ──
	r.orgUnits[wsID]["org-01"] = domain.OrgUnit{
		ID:             "org-01",
		WorkspaceID:    wsID,
		Code:           "ORG-EXEC",
		Name:           "Executive Leadership & Strategy Office",
		Type:           domain.OrgEnterprise,
		HeadRole:       "Chief Executive Officer",
		CostCenterCode: "CC-1000",
		HeadcountFTE:   12.0,
		Location:       "Global HQ - London",
		Description:    "Overall strategic direction, governance, and capital allocation.",
		CreatedAt:      now,
		UpdatedAt:      now,
	}
	r.orgUnits[wsID]["org-02"] = domain.OrgUnit{
		ID:             "org-02",
		WorkspaceID:    wsID,
		Code:           "ORG-DIGITAL",
		Name:           "Digital Commercial & Experience Division",
		Type:           domain.OrgDivision,
		ParentID:       strPtr("org-01"),
		HeadRole:       "Chief Commercial Officer",
		CostCenterCode: "CC-2100",
		HeadcountFTE:   145.0,
		Location:       "London & Dublin",
		Description:    "E-Commerce, Mobile Applications, Digital Marketing, and Customer Experience.",
		CreatedAt:      now,
		UpdatedAt:      now,
	}
	r.orgUnits[wsID]["org-03"] = domain.OrgUnit{
		ID:             "org-03",
		WorkspaceID:    wsID,
		Code:           "ORG-SUPPLY",
		Name:           "Global Logistics & Fulfillment Division",
		Type:           domain.OrgDivision,
		ParentID:       strPtr("org-01"),
		HeadRole:       "Chief Supply Chain Officer",
		CostCenterCode: "CC-3400",
		HeadcountFTE:   420.0,
		Location:       "Frankfurt, Manchester, Chicago",
		Description:    "Warehouse operations, 3PL logistics, inventory planning, and last-mile operations.",
		CreatedAt:      now,
		UpdatedAt:      now,
	}

	r.businessFunctions[wsID]["bf-01"] = domain.BusinessFunction{
		ID:          "bf-01",
		WorkspaceID: wsID,
		Code:        "BF-COMMERCE",
		Name:        "Omnichannel Commercial Operations",
		Description: "Logical function encompassing merchandising, pricing, digital storefronts, and checkout.",
		Owner:       "Chief Commercial Officer",
		OrgUnitIDs:  []string{"org-02"},
		CreatedAt:   now,
		UpdatedAt:   now,
	}
	r.businessFunctions[wsID]["bf-02"] = domain.BusinessFunction{
		ID:          "bf-02",
		WorkspaceID: wsID,
		Code:        "BF-FULFILLMENT",
		Name:        "Inventory & Logistics Management",
		Description: "Logical function encompassing warehouse stocking, order picking, and carrier dispatch.",
		Owner:       "Chief Supply Chain Officer",
		OrgUnitIDs:  []string{"org-03"},
		CreatedAt:   now,
		UpdatedAt:   now,
	}

	r.businessRoles[wsID]["role-01"] = domain.BusinessRole{
		ID:                  "role-01",
		WorkspaceID:         wsID,
		Code:                "ROLE-BA-LEAD",
		Title:               "Lead Business Architect",
		Description:         "Responsible for capability mapping, value stream optimization, and strategy alignment.",
		OrgUnitID:           strPtr("org-01"),
		WorkdayJobProfileID: "WD-JOB-ARCH-001",
		StandardRateUSD:     140.0,
		AllocatedFTE:        4.0,
		CreatedAt:           now,
		UpdatedAt:           now,
	}
	r.businessRoles[wsID]["role-02"] = domain.BusinessRole{
		ID:                  "role-02",
		WorkspaceID:         wsID,
		Code:                "ROLE-PRODUCT-MGR",
		Title:               "Digital Product Manager",
		Description:         "Owns customer-facing product features, conversion metrics, and roadmap execution.",
		OrgUnitID:           strPtr("org-02"),
		WorkdayJobProfileID: "WD-JOB-PROD-004",
		StandardRateUSD:     115.0,
		AllocatedFTE:        18.0,
		CreatedAt:           now,
		UpdatedAt:           now,
	}

	// ── 6. Business Services & Products ──
	r.businessServices[wsID]["bs-01"] = domain.BusinessService{
		ID:                 "bs-01",
		WorkspaceID:        wsID,
		Code:               "BS-CHECKOUT-API",
		Name:               "Universal Fast-Checkout Service",
		Description:        "Unified digital service providing biometric auth, cart validation, and payment settlement.",
		Nature:             domain.ServiceCustomerFacing,
		Status:             "Active",
		OwnerOrgUnitID:     strPtr("org-02"),
		OwnerRole:          "Director of E-Commerce",
		SLAAvailabilityPct: 99.99,
		SLAResponseTimeHours: 0.001, // sub-second
		SupportedChannels: []domain.DeliveryChannel{
			domain.ChannelDigitalWeb,
			domain.ChannelMobileApp,
			domain.ChannelPhysicalStore,
			domain.ChannelAPIOpen,
		},
		TargetCustomerSegments: []string{"Retail Shoppers", "VIP Members"},
		RealizingCapabilityIDs: []string{"cap-01", "cap-02", "cap-06"},
		CreatedAt:              now,
		UpdatedAt:              now,
	}
	r.products[wsID]["prod-01"] = domain.Product{
		ID:                 "prod-01",
		WorkspaceID:        wsID,
		Code:               "PROD-LOYALTY-PLUS",
		Name:               "Enterprise Plus Membership Pass",
		Description:        "Premium annual subscription granting unlimited same-day metro delivery and exclusive discount tiers.",
		MarketSegment:      "Affluent Digital Shoppers",
		PricingModel:       "Subscription ($99/year)",
		LifecycleStage:     "Growth",
		ProductManager:     "Digital Product Manager (Loyalty)",
		BusinessServiceIDs: []string{"bs-01"},
		CreatedAt:          now,
		UpdatedAt:          now,
	}

	// ── 7. Business Information Concepts & Glossary ──
	r.infoConcepts[wsID]["bic-01"] = domain.BusinessInformationConcept{
		ID:                  "bic-01",
		WorkspaceID:         wsID,
		Code:                "BIC-CUSTOMER",
		Name:                "Customer Master Concept",
		Description:         "Authoritative business entity representing an individual or organization transacting with the enterprise.",
		Classification:     domain.ClassificationMasterData,
		DomainOwnerRole:     "Head of Customer Data Governance",
		AuthoritativeSource: "Enterprise Customer Master / Workday HCM",
		RelatedCapabilityIDs: []string{"cap-01", "cap-02"},
		Attributes: []domain.ConceptAttribute{
			{Name: "CustomerID", Type: "Identifier", Description: "Unique global customer UUID", IsKey: true},
			{Name: "EmailAddress", Type: "Text", Description: "Primary verified communication email", IsPII: true},
			{Name: "KYCStatus", Type: "Text", Description: "Verification status: Unverified, Pending, Tier1, Tier2"},
			{Name: "LoyaltyTier", Type: "Text", Description: "Bronze, Silver, Gold, Platinum"},
		},
		Tags:      []string{"MasterData", "Customer360", "GDPR-Scoped"},
		CreatedAt: now,
		UpdatedAt: now,
	}
	r.infoConcepts[wsID]["bic-02"] = domain.BusinessInformationConcept{
		ID:                  "bic-02",
		WorkspaceID:         wsID,
		Code:                "BIC-ORDER",
		Name:                "Customer Purchase Order",
		Description:         "Transactional record capturing committed customer intent to purchase products.",
		Classification:     domain.ClassificationTransactional,
		DomainOwnerRole:     "Director of Order Management",
		AuthoritativeSource: "Central Order Processing Engine",
		RelatedCapabilityIDs: []string{"cap-01", "cap-05", "cap-06"},
		Attributes: []domain.ConceptAttribute{
			{Name: "OrderID", Type: "Identifier", Description: "Unique order reference", IsKey: true},
			{Name: "CustomerID", Type: "Identifier", Description: "Foreign key to Customer Master", IsKey: false},
			{Name: "TotalGrossAmountUSD", Type: "Currency", Description: "Total charged including taxes and shipping"},
			{Name: "OrderStatus", Type: "Text", Description: "Authorized, Allocated, InTransit, Delivered, Cancelled"},
		},
		Tags:      []string{"Transactional", "OrderToCash"},
		CreatedAt: now,
		UpdatedAt: now,
	}

	r.terms[wsID]["term-01"] = domain.BusinessTerm{
		ID:             "term-01",
		WorkspaceID:    wsID,
		Term:           "Customer 360",
		Definition:     "A single, holistic view of a customer's profile, transaction history, preferences, and active loyalty balance aggregated across digital and physical touchpoints.",
		DomainCategory: "Customer Relations",
		Steward:        "Chief Commercial Officer",
		Synonyms:       []string{"Single Customer View", "Unified Profile"},
		ConceptID:      strPtr("bic-01"),
		CreatedAt:      now,
		UpdatedAt:      now,
	}
	r.terms[wsID]["term-02"] = domain.BusinessTerm{
		ID:             "term-02",
		WorkspaceID:    wsID,
		Term:           "Flow Efficiency",
		Definition:     "The percentage of total lead time in a value stream spent actively performing value-adding work (Processing Time divided by Lead Time).",
		DomainCategory: "Business Process Architecture",
		Steward:        "Lead Business Architect",
		Synonyms:       []string{"Process Cycle Efficiency (PCE)"},
		CreatedAt:      now,
		UpdatedAt:      now,
	}

	// ── 8. Transformation Initiatives & 3 Horizons Roadmap ──
	r.initiatives[wsID]["init-01"] = domain.Initiative{
		ID:                   "init-01",
		WorkspaceID:          wsID,
		Code:                 "INIT-BIOMETRIC-CHECKOUT",
		Name:                 "One-Click Biometric Digital Checkout Modernization",
		Description:          "Uplift customer onboarding and checkout capabilities by integrating WebAuthn biometric passkeys and automated fraud scoring.",
		Horizon:              domain.Horizon1Core,
		Status:               domain.StatusActive,
		BudgetUSD:            1250000.0,
		ExpectedROI:          "+18% Mobile Conversion Rate, $32M Annual GMV Lift",
		StartDate:            "2026-01-15",
		TargetCompletionDate: "2026-11-30",
		SponsorRole:          "Chief Commercial Officer",
		LeadArchitect:        "Lead Business Architect",
		Milestones: []domain.TransformationMilestone{
			{Title: "Architecture Blueprint & Workday Integration Sign-off", TargetDate: "2026-03-31", IsCompleted: true, Deliverable: "Signed Architecture Decision Record"},
			{Title: "Beta Pilot Launch in UK/Ireland", TargetDate: "2026-08-15", IsCompleted: false, Deliverable: "Live Mobile App Beta Build"},
			{Title: "Global Rollout & Legacy Decommissioning", TargetDate: "2026-11-30", IsCompleted: false, Deliverable: "100% Production Traffic"},
		},
		ImpactedCapabilityIDs: []string{"cap-02"},
		TargetObjectiveIDs:    []string{"obj-01"},
		TargetValueStreamIDs:  []string{"vs-01"},
		CreatedAt:             now,
		UpdatedAt:             now,
	}
	r.initiatives[wsID]["init-02"] = domain.Initiative{
		ID:                   "init-02",
		WorkspaceID:          wsID,
		Code:                 "INIT-AI-INVENTORY-ROUTING",
		Name:                 "Autonomous Multi-Hub Inventory Optimization Engine",
		Description:          "Deploy machine learning demand forecasting to dynamically allocate warehouse inventory and minimize cross-country shipping.",
		Horizon:              domain.Horizon2Emerging,
		Status:               domain.StatusApproved,
		BudgetUSD:            2400000.0,
		ExpectedROI:          "-$14M Annual Logistics Cost, 35% Faster Transit",
		StartDate:            "2026-06-01",
		TargetCompletionDate: "2027-05-31",
		SponsorRole:          "Chief Supply Chain Officer",
		LeadArchitect:        "Principal Enterprise Architect",
		Milestones: []domain.TransformationMilestone{
			{Title: "Predictive Model Training on 3-Year Order Data", TargetDate: "2026-09-30", IsCompleted: false, Deliverable: "Model Accuracy Validation Report"},
			{Title: "Integration with Regional Warehouse WMS Hubs", TargetDate: "2027-02-28", IsCompleted: false, Deliverable: "Automated Routing API"},
		},
		ImpactedCapabilityIDs: []string{"cap-05"},
		TargetObjectiveIDs:    []string{"obj-02"},
		TargetValueStreamIDs:  []string{"vs-01"},
		CreatedAt:             now,
		UpdatedAt:             now,
	}
	r.initiatives[wsID]["init-03"] = domain.Initiative{
		ID:                   "init-03",
		WorkspaceID:          wsID,
		Code:                 "INIT-SPATIAL-COMMERCE",
		Name:                 "Spatial Commerce & Augmented Reality Try-On",
		Description:          "Explore next-generation immersive spatial computing shopping experiences for flagship luxury categories.",
		Horizon:              domain.Horizon3Transform,
		Status:               domain.StatusProposed,
		BudgetUSD:            850000.0,
		ExpectedROI:          "Brand Differentiation & First-Mover Advantage",
		StartDate:            "2027-01-01",
		TargetCompletionDate: "2027-12-31",
		SponsorRole:          "Head of Innovation",
		LeadArchitect:        "Emerging Tech Architect",
		ImpactedCapabilityIDs: []string{"cap-01"},
		CreatedAt:             now,
		UpdatedAt:             now,
	}

	// ── 9. Audit Logs ──
	r.audits[wsID] = []domain.AuditEntry{
		{
			ID:          "aud-01",
			WorkspaceID: wsID,
			EntityType:  "Initiative",
			EntityID:    "init-01",
			Action:      "UPDATE",
			PerformedBy: "Lead Business Architect (Workday User WD-992)",
			Timestamp:   now.Add(-2 * time.Hour),
			Details:     "Completed milestone: Architecture Blueprint & Workday Integration Sign-off",
		},
		{
			ID:          "aud-02",
			WorkspaceID: wsID,
			EntityType:  "Capability",
			EntityID:    "cap-02",
			Action:      "UPDATE",
			PerformedBy: "VP Digital Experience",
			Timestamp:   now.Add(-24 * time.Hour),
			Details:     "Updated target maturity from 4.2 to 4.6 following Horizon 1 initiative funding approval",
		},
	}
}

func strPtr(s string) *string {
	return &s
}
